capital_cities/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("capitals.urls")),
]

capitals/urls.py
from django.urls import path
from .views import HomePageView, NewCapitalView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("new/", NewCapitalView.as_view(), name="capital_new"),
]

capitals/models.py
from django.db import models
from django.urls import reverse


class Capital(models.Model):
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.city}, {self.country}"

    def get_absolute_url(self):
        return reverse("home")

capitals/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from .models import Capital


class HomePageView(ListView):
    template_name = "home.html"
    model = Capital

class NewCapitalView(CreateView):
    template_name = 'capital_new.html'
    model = Capital
    fields = ['city', 'country']

templates/base.html
<html>
  <head>
    <title>Capital Cities</title>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <div class="container my-3">
      <header class="border-bottom border-secondary pb-1 d-flex align-items-center">
        <div class="col-9 display-3">
          <a href="{% url 'home' %}">Capital Cities</a>
        </div>
        <div class="col">
            <a class="btn btn-outline-primary" href="{% url 'capital_new' %}">+ New Capital</a>
        </div>
      </header>
      {% block content %}
      {% endblock content %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </div>
    </div>
  </body>
</html>

templates/capital_new.html
{% extends "base.html" %}
{% block content %}
<div class="my-2">
  <h2 class="display-6">Add a New Capital to the List</h2>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" class="btn btn-outline-primary">
  </form>
</div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block content %}
{% for capital in capital_list %}
<div class="my-2">
  <h3 class="display-6">{{ capital.city }} is the capital of {{ capital.country }}</h3>
</div>
{% endfor %}
{% endblock content %}